### ISSUE TITLE
请教这3个值是怎么才可以获取到的呢？

### ISSUE THREAD

**Issue by hbstarjason** [jiongjiongJOJO/womail_checkin#1]
DATA: 
        KEY: 
        URL:

**Comment by jiongjiongJOJO** [comment]
这个代码写了很久了，我只记得当时抓包，然后抓到了一个链接，然后就写了代码...
等我有时间研究研究再回复你吧。。。
key是pushplus 的token
data和url都是抓包抓出来的。

**Comment by jiongjiongJOJO** [comment]
DATA的格式为：

`
{
      "womail_url": "https://nyan.mail.wo.cn/cn/sign/index/index?mobile=xxxxxx&userName=&openId=xxxxxx"
 }
`

其中的url链接是打开公众号里的“签到有礼”抓包得到的，找准域名，即可抓取到。

**Comment by jiongjiongJOJO** [comment]
URL这个参数我找不到了，原因如下：
沃邮箱的页面发生了更新，这个是之前的抽奖活动，目前页面删除这个活动的链接，但是，活动还可以继续通过脚本抽奖。
因为找不到入口，所以，我也没法提供在哪里获取的数据，抱歉哈。。

**Comment by jiongjiongJOJO** [comment]
这个仓库源自于“Sitoi / dailycheckin”，我稍作了修改，目前不添加url这个参数也是可以正常运行的，只是不会参与抽奖的活动，不影响其他功能的使用。

**Comment by jiongjiongJOJO** [comment]
已更新脚本，请重新fork，不再需要url参数了，也可以参与抽奖活动。
