### ISSUE TITLE
签到内容补全以及部分倒扣积分bug

### ISSUE THREAD

**Issue by zaxbpc** [jiongjiongJOJO/womail_checkin#2]
# 补全，积分x2
![womail-1.png](https://img10.360buyimg.com/ddimg/jfs/t1/189879/24/18536/280078/6119e332E8734f88e/57abf83573b6ec09.png)
![womail-2.png](https://img12.360buyimg.com/ddimg/jfs/t1/202155/23/1623/291149/6119e32eE5098322d/d5b4a37b36d2cdc9.png)
# 反薅羊毛
![womail-3.jpg](https://img12.360buyimg.com/ddimg/jfs/t1/201431/31/1841/151300/6119e330E4b5b7618/5a1e815c0e2cb747.jpg)

**Comment by jiongjiongJOJO** [comment]
懒得修复，原因如下
1.就是懒，不想弄
2.代码不是我写的，代码逻辑真的烂的一批（作者看到见谅，真的看起来很头疼）
3.最近比较忙（学业）
4.后续我会重写这个代码，所以，这个暂时不管了。

**Comment by zaxbpc** [comment]
主要是抓包不太会，不然也能提些PR 🤣

**Comment by jiongjiongJOJO** [comment]
> 主要是抓包不太会，不然也能提些PR 🤣

已更新，国庆节爆肝~~
国庆快乐！
